### ISSUE TITLE
nextcloud doesnt start up

### ISSUE THREAD

**Issue by kampfq** [soudis/habidat-setup#1]
**Describe the bug**
installing the nextcloud container is not possible. errormessage:

NEXTCLOUD   | Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'nextcloud'@'172.22.0.7' (using password: YES)

**To Reproduce**
1. clone master branch
2. run './habidat.sh install nextcloud'

**Expected behavior**
container is starting up

**Server:**
 - OS: centos 8
 - Docker: Docker CE, docker-compose version 1.25.0, build 0a186604

**Comment by soudis** [comment]
Can you pleas provide your setup.env?

**Comment by kampfq** [comment]
```
export HABIDAT_TITLE="Feuerwache Cloud"
export HABIDAT_DESCRIPTION="All the things!"
export HABIDAT_LOGO=habidat.png
export HABIDAT_ADMIN_EMAIL=kampfq@posteo.de
export HABIDAT_ADMIN_PASSWORD=generate
export HABIDAT_PROTOCOL=https
export HABIDAT_DOMAIN=feuerwache.de
export HABIDAT_NEXTCLOUD_SUBDOMAIN=cloud
export HABIDAT_NEXTCLOUD_DEFAULTQUOTA="2 GB"
export HABIDAT_DISCOURSE_SUBDOMAIN=discourse
export HABIDAT_DIREKTKREDIT_SUBDOMAIN=direktkredit
export HABIDAT_USER_SUBDOMAIN=user
export HABIDAT_MEDIAWIKI_SUBDOMAIN=mediawiki
export HABIDAT_DOKUWIKI_SUBDOMAIN=dokuwiki
export HABIDAT_MAILTRAIN_PUBLIC_SUBDOMAIN=lists
export HABIDAT_MAILTRAIN_SUBDOMAIN=mailtrain
export HABIDAT_MAILTRAIN_SANDBOX_SUBDOMAIN=sandbox.mailtrain
export HABIDAT_LDAP_BASE=dc=feuerwache,dc=de
export HABIDAT_SMTP_EMAILFROM=admin@example.com
export HABIDAT_SMTP_HOST=mail.xaok.org
export HABIDAT_SMTP_PORT=25
export HABIDAT_SMTP_USER=
export HABIDAT_SMTP_PASSWORD=
export HABIDAT_SMTP_TLS=false
export HABIDAT_SMTP_AUTHMETHOD=none       #none, plain or login
export HABIDAT_DOCKER_PREFIX=habidatlive
export HABIDAT_CREATE_SELFSIGNED=true
export HABIDAT_LETSENCRYPT=true
export HABIDAT_SSO=false
export HABIDAT_EXISTING_NGINX_GENERATOR_NETWORK=
export HABIDAT_EXISTING_BACKEND_NETWORK=
export HABIDAT_BACKUP_DIR=/var/opt/habidat
export COMPOSE_HTTP_TIMEOUT=200
```

**Comment by soudis** [comment]
Hmm.. everything looks just fine, I'm not really sure what happened there, but have you already tried to remove and install nextcloud again (no "have you tried to turn it off an on again"-jokes please ;)) ?

`./habidat.sh rm nextcloud`
`./habidat.sh install nextcloud`

could be that there is a problem with the generated nextcloud DB password and it works if you cust generate it again. Let me know if it works, cause I would need to fix that.

**Comment by kampfq** [comment]
i tried to remove and installed it again, even a clean checkout doesn`t help :(

**Comment by soudis** [comment]
Just did a clean checkout and install myself and it did work... I'm a little clueless. What's the specs of your server? And are there any other services running on the machine? And did you install envsubst (gettext-base) and curl on the machine?

BTW, please change the SMTP_HOST to a SMTP server you have access to (the one from posteo maybe). Otherwise the e-mail functionalities will not work.

**Comment by kampfq** [comment]
on centos you have to install gettext
its working, thx :)
https://centos.pkgs.org/8/centos-baseos-x86_64/gettext-0.19.8.1-17.el8.x86_64.rpm.html

**Comment by soudis** [comment]
nice :)

please keep in mind that this project is still in development, so there maybe bigger updates in the near future that may require a little tinkering to keep it running. I would not recommend using this in an production environment yet.
